# rumdl configuration file
# https://rumdl.dev/

[global]

disable = [
  # Using tabs in some unfenced code blocks.
  "MD010",

  # Some code blocks end with a tab, which is seen as a "blank line".
  "MD012",

  # No max line lenght.
  "MD013",

  # Some fenced code blocks do not have a language.
  "MD040",

  # Most code blocks are not fenced, to be able to extract them easily.
  "MD046",
]

exclude = [
  ".git",
]

# Unordered list style
[MD004]
style = "dash"

# Unordered list indentation
[MD007]
indent = 2

# HTML tags
[MD033]
allowed-elements = [
  "kbd"
]
