# rumdl configuration file
# https://rumdl.dev/

[global]

disable = [
  # No max line lenght.
  "MD013",

  # SKILL.md files has frontmatter.
  "MD041",

  # Most code blocks are not fenced, to be able to extract them easily.
  "MD046",
]

exclude = [
  ".git",
]

# Unordered list style
[MD004]
style = "dash"

# Unordered list indentation
[MD007]
indent = 2

# HTML tags
[MD033]
allowed-elements = [
  "kbd"
]
