# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Run all actions then check
    cmds:
      - task: Agents
      - task: Claude
      - task: EditorConfig
      - task: GitHub
      - task: Homebrew
      - task: Zsh
      - task: npm
      # Keep "check" at the end.
      - task: check

  check:
    desc: Check markdown files
    cmds:
      - rumdl check .

  # Follows a sorted list of actions.

  Agents:
    cmds:
      - markdown2code --lang sh Agents/README.md > Agents/setup.sh

  Claude:
    cmds:
      - markdown2code --lang md Claude/README.md > Claude/CLAUDE.md
      - markdown2code --lang json Claude/README.md > Claude/settings.json

  EditorConfig:
    cmds:
      - markdown2code --lang ini EditorConfig/README.md > EditorConfig/dot-editorconfig

  GitHub:
    cmds:
      - markdown2code --lang sh GitHub/README.md > GitHub/setup.sh

  Homebrew:
    cmds:
      - markdown2code --lang sh Homebrew/README.md > Homebrew/setup.sh

  Zsh:
    cmds:
      - markdown2code --lang zsh Zsh/README.md > Zsh/config.zsh

  npm:
    cmds:
      - markdown2code --lang sh npm/README.md > npm/setup.sh
