# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Run all actions then check
    cmds:
      - task: Agents
      - task: Claude
      - task: EditorConfig
      - task: Git
      - task: GitHub
      - task: Homebrew
      - task: Neovim
      - task: Zsh
      - task: npm
      - task: shell
      # Keep "check" at the end.
      - task: check

  check:
    desc: Check markdown files
    cmds:
      - rumdl check .

  # Follows a sorted list of actions.

  Agents:
    cmds:
      - markdown2code --lang sh Agents/README.md > Agents/setup.sh

  Claude:
    cmds:
      - markdown2code --lang md Claude/README.md > Claude/CLAUDE.md
      - markdown2code --lang json Claude/README.md > Claude/settings.json
      - markdown2code --lang sh Claude/statusline.md > Claude/statusline.sh

  EditorConfig:
    cmds:
      - markdown2code --lang ini EditorConfig/README.md > EditorConfig/dot-editorconfig

  Git:
    cmds:
      - markdown2code --lang sh Git/README.md > Git/setup.sh

  GitHub:
    cmds:
      - markdown2code --lang sh GitHub/README.md > GitHub/setup.sh

  Homebrew:
    cmds:
      - markdown2code --lang sh Homebrew/README.md > Homebrew/setup.sh

  Neovim:
    cmds:
      - markdown2code --lang sh Neovim/README.md > Neovim/setup.sh
      - markdown2code --lang lua Neovim/README.md > Neovim/init.lua

  Zsh:
    cmds:
      - markdown2code --lang zsh Zsh/README.md > Zsh/config.zsh
      - markdown2code --lang sh Zsh/README.md > Zsh/setup.sh
      - markdown2code --lang sh Zsh/completions.md > Zsh/completions.sh
      - markdown2code --lang sh Zsh/dependencies.md > Zsh/dependencies.sh

  npm:
    cmds:
      - markdown2code --lang sh npm/README.md > npm/setup.sh

  shell:
    cmds:
      - markdown2code --lang sh shell/README.md > shell/setup.sh
      - markdown2code --lang sh shell/aliases.md > shell/aliases.sh
