-- Do not edit this file,
-- go to github.com/fibo/home/Neovim/README.md

vim.g.mapleader = ' '
-- Treat dash as part of a word.
vim.opt.iskeyword:append('-')

vim.o.number = true
vim.o.cursorline = true
-- Edit, split or open a tab starting from current file folder.
vim.keymap.set('n', ',e', ':edit <C-R>=expand("%:p:h") . "/" <CR>', { noremap = true })
vim.keymap.set('n', ',s', ':split <C-R>=expand("%:p:h") . "/" <CR>', { noremap = true })
vim.keymap.set('n', ',t', ':tabnew <C-R>=expand("%:p:h") . "/" <CR>', { noremap = true })
-- Highlight when yanking (copying) text.
vim.api.nvim_create_autocmd('TextYankPost', {
  desc = 'Highlight when yanking (copying) text',
  callback = function()
    vim.hl.on_yank()
  end,
})
-- Automatically disable search highlighting.
vim.cmd('packadd! nohlsearch')
vim.pack.add({
  -- Git integration
  'https://github.com/tpope/vim-fugitive',
  'https://github.com/lewis6991/gitsigns.nvim',

  -- Fuzzy Finder
  'https://github.com/junegunn/fzf',
  'https://github.com/junegunn/fzf.vim',
})

require('gitsigns').setup {}
-- Find files.
vim.api.nvim_set_keymap("n", "<leader>f", [[<Cmd>:Files!<CR>]], {})
-- Find a string under the cursor.
vim.api.nvim_set_keymap("n", "<leader>s", [[:Rg! <C-R><C-W><CR>]], {})
-- Open ripgrep.
vim.api.nvim_set_keymap("n", "<leader>g", [[:RG! <CR>]], {})
-- List buffers.
vim.api.nvim_set_keymap("n", "<leader>b", [[<Cmd>:Buffers!<CR>]], {})
-- Quit terminal with `Ctrl-d`.
vim.keymap.set('t', '<C-d>', [[<Cmd>quit<CR>]], { noremap = true })
-- Open a terminal at the bottom.
vim.keymap.set('n', '<leader>t', function()
  vim.cmd('botright new') -- Open a new horizontal split at the very bottom
  vim.cmd('terminal')     -- Turn that split into a terminal
  vim.cmd('resize 12')    -- Set a consistent height
end, { desc = 'Terminal at bottom' })
-- When a terminal opens, hide line numbers, sign column and status line, then enter insert mode.
vim.api.nvim_create_autocmd("TermOpen", {
  callback = function()
    vim.opt_local.number = false
    vim.opt_local.relativenumber = false
    vim.opt_local.signcolumn = "no"
    vim.opt.laststatus = 0  -- Hide status line
    vim.cmd('startinsert')  -- Jump straight into typing mode
  end,
})
